In [1]:
import pandas as pd

df = pd.read_csv("ncr_ride_bookings.csv")

df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [2]:
df.shape

(150000, 21)

In [3]:
df.columns.tolist()

['Date',
 'Time',
 'Booking ID',
 'Booking Status',
 'Customer ID',
 'Vehicle Type',
 'Pickup Location',
 'Drop Location',
 'Avg VTAT',
 'Avg CTAT',
 'Cancelled Rides by Customer',
 'Reason for cancelling by Customer',
 'Cancelled Rides by Driver',
 'Driver Cancellation Reason',
 'Incomplete Rides',
 'Incomplete Rides Reason',
 'Booking Value',
 'Ride Distance',
 'Driver Ratings',
 'Customer Rating',
 'Payment Method']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [5]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [6]:
df.head(10)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
5,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,...,NaN,NaN,NaN,NaN,NaN,316.0,4.85,4.1,4.6,UPI
6,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,...,NaN,NaN,NaN,NaN,NaN,640.0,41.24,4.0,4.1,UPI
7,2024-03-19,17:37:37,"""CNR6568000""",Completed,"""CID8610436""",Auto,Mayur Vihar,Cyber Hub,12.1,16.5,...,NaN,NaN,NaN,NaN,NaN,136.0,6.56,4.4,4.2,UPI
8,2024-09-14,12:49:09,"""CNR4510807""",No Driver Found,"""CID7873618""",Go Sedan,Noida Sector 62,Noida Sector 18,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2024-12-16,19:06:48,"""CNR7721892""",Incomplete,"""CID5214275""",Auto,Rohini,Adarsh Nagar,6.1,26.0,...,NaN,NaN,NaN,1.0,Other Issue,135.0,10.36,NaN,NaN,Cash

In [7]:
df["Booking Status"].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [8]:
df["Vehicle Type"].value_counts()

Vehicle Type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

In [9]:
df["Cancelled Rides by Driver"].value_counts(dropna=False)

Cancelled Rides by Driver
NaN    123000
1.0     27000
Name: count, dtype: int64

In [10]:

df["Incomplete Rides"].value_counts(dropna=False)

Incomplete Rides
NaN    141000
1.0      9000
Name: count, dtype: int64

In [13]:
df[["Avg VTAT", "Avg CTAT", "Booking Value", "Ride Distance",
    "Driver Ratings", "Customer Rating"]].describe()

,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,4277.000000,50.000000,5.000000,5.000000

In [14]:
df[["Avg VTAT", "Avg CTAT", "Booking Value", "Ride Distance",
    "Driver Ratings", "Customer Rating"]].min()

Avg VTAT            2.0
Avg CTAT           10.0
Booking Value      50.0
Ride Distance       1.0
Driver Ratings      3.0
Customer Rating     3.0
dtype: float64

In [15]:
df[["Avg VTAT", "Avg CTAT", "Booking Value", "Ride Distance",
    "Driver Ratings", "Customer Rating"]].max()

Avg VTAT             20.0
Avg CTAT             45.0
Booking Value      4277.0
Ride Distance        50.0
Driver Ratings        5.0
Customer Rating       5.0
dtype: float64

In [16]:
df["Booking ID"].duplicated().sum()

np.int64(1233)

In [17]:
df["Booking ID"].nunique()

148767

In [18]:
df["Customer ID"].nunique()

148788

In [19]:
duplicates = df[df["Booking ID"].duplicated(keep=False)].sort_values("Booking ID")

duplicates[[
    "Booking ID",
    "Date",
    "Time",
    "Booking Status",
    "Customer ID",
    "Vehicle Type",
    "Pickup Location",
    "Drop Location"
]].head(30)

,Booking ID,Date,Time,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location
81334,"""CNR1026036""",2024-10-15,18:17:23,Completed,"""CID6480133""",Go Mini,Khandsa,Ashok Vihar
9192,"""CNR1026036""",2024-07-21,17:59:41,No Driver Found,"""CID6974869""",Go Mini,Seelampur,Nehru Place
9587,"""CNR1029172""",2024-12-17,19:19:02,Completed,"""CID6382731""",Auto,Inderlok,Laxmi Nagar
1353,"""CNR1029172""",2024-01-19,17:00:57,Incomplete,"""CID2615731""",Bike,Jhilmil,Narsinghpur
82029,"""CNR1051228""",2024-11-05,16:50:20,Completed,"""CID3177617""",Auto,Dwarka Sector 21,Nehru Place
110412,"""CNR1051228""",2024-01-31,08:42:04,Completed,"""CID5242056""",Premier Sedan,Arjangarh,Yamuna Bank
87333,"""CNR1056023""",2024-04-20,23:16:21,Completed,"""CID9367665""",Premier Sedan,Badshahpur,Sultanpur
120008,"""CNR1056023""",2024-07-07,17:18:49,Incomplete,"""CID4890470""",Go Sedan,Meerut,Tilak Nagar
71570,"""CNR1058956""",2024-02-12,19:02:47,Cancelled by Customer,"""CID2451799""",Premier Sedan,Patel Chowk,Kaushambi
38548,"""CNR1058956""",2024-10-15,13:33:55,Completed,"""CID1882606""",Go Mini,Badshahpur,MG Road
92822,"""CNR1071255""",2024-03-24,11:11:19,Cancelled by Driver,"""CID4222557""",Go Mini,MG Road,Moolchand
94087,"""CNR1071255""",2024-03-21,07:35:07,Completed,"""CID4439810""",Go Sedan,Ghaziabad,Ramesh Nagar
23113,"""CNR1076471""",2024-02-12,12:58:19,Completed,"""CID3616321""",Bike,Rohini West,Anand Vihar ISBT
18828,"""CNR1076471""",2024-10-07,20:06:47,Completed,"""CID8425781""",Go Sedan,Ashok Vihar,Yamuna Bank
82485,"""CNR1077779""",2024-08-20,11:29:28,Completed,"""CID2252556""",Go Mini,Vasant Kunj,Indraprastha
87568,"""CNR1077779""",2024-11-05,17:32:53,Cancelled by Customer,"""CID6213303""",Premier Sedan,Greater Kailash,Madipur
26279,"""CNR1079962""",2024-11-27,20:54:07,Completed,"""CID1039185""",Go Sedan,Mansarovar Park,Model Town
148881,"""CNR1079962""",2024-12-15,09:21:59,Completed,"""CID1210517""",Auto,Nirman Vihar,Maidan Garhi
100164,"""CNR1091682""",2024-07-04,15:46:39,Cancelled by Customer,"""CID1131593""",Go Mini,Vishwavidyalaya,Botanical Garden
111121,"""CNR1091682""",2024-08-13,10:39:17,Completed,"""CID1590844""",eBike,Punjabi Bagh,Khan Market
83416,"""CNR1125525""",2024-09-18,10:08:25,Cancelled by Customer,"""CID1702916""",Auto,Seelampur,Chhatarpur
24197,"""CNR1125525""",2024-07-28,02:06:31,Cancelled by Driver,"""CID5846635""",eBike,Nehru Place,Sohna Road
7624,"""CNR1129818""",2024-02-02,10:53:00,Completed,"""CID9692280""",Bike,Greater Kailash,Ramesh Nagar
111474,"""CNR1129818""",2024-01-30,20:38:35,Cancelled by Driver,"""CID8993312""",Bike,Civil Lines Gurgaon,Manesar
57588,"""CNR1130025""",2024-11-17,12:20:34,Completed,"""CID4646812""",Bike,Gurgaon Sector 29,Kanhaiya Nagar
108063,"""CNR1130025""",2024-06-22,05:06:13,Cancelled by Driver,"""CID5686876""",Auto,Subhash Nagar,Kaushambi
83117,"""CNR1143952""",2024-12-30,18:18:50,Completed,"""CID6138660""",Bike,IGI Airport,Rajouri Garden
97926,"""CNR1143952""",2024-01-17,15:04:57,Cancelled by Driver,"""CID1795030""",Auto,Noida Sector 62,Ghitorni Village
96732,"""CNR1156110""",2024-07-26,11:40:42,Cancelled by Customer,"""CID6894365""",Premier Sedan,Jor Bagh,Welcome
59038,"""CNR1156110""",2024-06-26,05:50:14,No Driver Found,"""CID9436591""",Go Mini,Qutub Minar,Huda City Centre

In [20]:
duplicates["Booking ID"].value_counts().head(20)

Booking ID
"CNR7642097"    3
"CNR7908610"    3
"CNR6337479"    3
"CNR7199036"    3
"CNR3648267"    3
"CNR7585544"    3
"CNR2726142"    3
"CNR5292943"    3
"CNR9603232"    3
"CNR7089920"    2
"CNR7083663"    2
"CNR7083602"    2
"CNR7069978"    2
"CNR7046122"    2
"CNR7093392"    2
"CNR7038047"    2
"CNR7037928"    2
"CNR7031110"    2
"CNR7030373"    2
"CNR7022060"    2
Name: count, dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
pd.crosstab(df["Booking Status"], df["Cancelled Rides by Driver"], dropna=False)

Cancelled Rides by Driver    1.0    NaN
Booking Status
Cancelled by Customer          0  10500
Cancelled by Driver        27000      0
Completed                      0  93000
Incomplete                     0   9000
No Driver Found                0  10500

In [23]:
pd.crosstab(
    df["Booking Status"],
    df["Cancelled Rides by Customer"],
    dropna=False
)

Cancelled Rides by Customer    1.0    NaN
Booking Status
Cancelled by Customer        10500      0
Cancelled by Driver              0  27000
Completed                        0  93000
Incomplete                       0   9000
No Driver Found                  0  10500

In [24]:
pd.crosstab(
    df["Booking Status"],
    df["Incomplete Rides"],
    dropna=False
)

Incomplete Rides        1.0    NaN
Booking Status
Cancelled by Customer     0  10500
Cancelled by Driver       0  27000
Completed                 0  93000
Incomplete             9000      0
No Driver Found           0  10500

In [25]:
pd.crosstab(
    df["Booking Status"],
    df["Driver Cancellation Reason"],
    dropna=False
)

Driver Cancellation Reason,Customer related issue,More than permitted people in there,Personal & Car related issues,The customer was coughing/sick,NaN
Booking Status,,,,,
Cancelled by Customer,0,0,0,0,10500
Cancelled by Driver,6837,6686,6726,6751,0
Completed,0,0,0,0,93000
Incomplete,0,0,0,0,9000
No Driver Found,0,0,0,0,10500

In [26]:
pd.crosstab(
    df["Booking Status"],
    df["Reason for cancelling by Customer"],
    dropna=False
)

Reason for cancelling by Customer,AC is not working,Change of plans,Driver asked to cancel,Driver is not moving towards pickup location,Wrong Address,NaN
Booking Status,,,,,,
Cancelled by Customer,1155,2353,2295,2335,2362,0
Cancelled by Driver,0,0,0,0,0,27000
Completed,0,0,0,0,0,93000
Incomplete,0,0,0,0,0,9000
No Driver Found,0,0,0,0,0,10500

In [27]:
pd.crosstab(
    df["Booking Status"],
    df["Incomplete Rides Reason"],
    dropna=False
)

Incomplete Rides Reason,Customer Demand,Other Issue,Vehicle Breakdown,NaN
Booking Status,,,,
Cancelled by Customer,0,0,0,10500
Cancelled by Driver,0,0,0,27000
Completed,0,0,0,93000
Incomplete,3040,2948,3012,0
No Driver Found,0,0,0,10500

In [28]:
df["Date"].min(), df["Date"].max()

('2024-01-01', '2024-12-30')

In [29]:
pd.to_datetime(df["Date"], errors="coerce").isna().sum()

np.int64(0)

In [30]:
pd.to_datetime(df["Time"], errors="coerce").isna().sum()

C:\Users\User\AppData\Local\Temp\ipykernel_17692\1937039861.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(df["Time"], errors="coerce").isna().sum()

np.int64(0)

In [31]:
df.loc[
    df["Booking Status"] == "Completed",
    ["Booking Value", "Ride Distance"]
].isna().sum()

Booking Value    0
Ride Distance    0
dtype: int64

In [32]:
df.loc[
    df["Booking Status"] == "Completed",
    ["Driver Ratings", "Customer Rating"]
].isna().sum()

Driver Ratings     0
Customer Rating    0
dtype: int64

In [33]:
df.loc[
    df["Booking Status"] == "Completed",
    "Payment Method"
].isna().sum()

np.int64(0)

In [34]:
df["Booking Status"].unique()

array(['No Driver Found', 'Incomplete', 'Completed',
       'Cancelled by Driver', 'Cancelled by Customer'], dtype=object)

In [35]:
df["Vehicle Type"].unique()

array(['eBike', 'Go Sedan', 'Auto', 'Premier Sedan', 'Bike', 'Go Mini',
       'Uber XL'], dtype=object)

In [36]:
df["Pickup Location"].nunique(), df["Pickup Location"].isna().sum()

(176, np.int64(0))

In [37]:
df["Drop Location"].nunique(), df["Drop Location"].isna().sum()

(176, np.int64(0))

In [39]:
pd.crosstab(
    df["Booking Status"],
    df["Avg CTAT"].isna()
)

Avg CTAT               False  True
Booking Status
Cancelled by Customer      0  10500
Cancelled by Driver        0  27000
Completed              93000      0
Incomplete              9000      0
No Driver Found            0  10500

In [40]:
pd.crosstab(
    df["Booking Status"],
    df["Booking Value"].isna()
)

Booking Value          False  True
Booking Status
Cancelled by Customer      0  10500
Cancelled by Driver        0  27000
Completed              93000      0
Incomplete              9000      0
No Driver Found            0  10500

In [41]:
pd.crosstab(
    df["Booking Status"],
    df["Ride Distance"].isna()
)

Ride Distance          False  True
Booking Status
Cancelled by Customer      0  10500
Cancelled by Driver        0  27000
Completed              93000      0
Incomplete              9000      0
No Driver Found            0  10500

In [42]:
pd.crosstab(
    df["Booking Status"],
    df["Driver Ratings"].isna()
)

Driver Ratings         False  True
Booking Status
Cancelled by Customer      0  10500
Cancelled by Driver        0  27000
Completed              93000      0
Incomplete                 0   9000
No Driver Found            0  10500

In [43]:
pd.crosstab(
    df["Booking Status"],
    df["Customer Rating"].isna()
)

Customer Rating        False  True
Booking Status
Cancelled by Customer      0  10500
Cancelled by Driver        0  27000
Completed              93000      0
Incomplete                 0   9000
No Driver Found            0  10500

In [44]:
pd.crosstab(
    df["Booking Status"],
    df["Payment Method"].isna()
)

Payment Method         False  True
Booking Status
Cancelled by Customer      0  10500
Cancelled by Driver        0  27000
Completed              93000      0
Incomplete              9000      0
No Driver Found            0  10500

In [45]:
print(df[["Date", "Time"]].dtypes)

Date    object
Time    object
dtype: object

In [46]:
df["Date"] = pd.to_datetime(df["Date"])

In [47]:
df["Date"].dtype

dtype('<M8[ns]')

In [48]:
df["Time"] = pd.to_datetime(df["Time"]).dt.time

C:\Users\User\AppData\Local\Temp\ipykernel_17692\3518047455.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Time"] = pd.to_datetime(df["Time"]).dt.time

In [49]:
df["Time"].dtype

dtype('O')

In [52]:
df["Time"] = pd.to_datetime(
    df["Time"].astype(str),
    format="%H:%M:%S"
)

In [53]:
df["Time"].dtype

dtype('<M8[ns]')

In [54]:
(df["Avg VTAT"] <= 0).sum(), (df["Avg CTAT"] <= 0).sum(), (df["Booking Value"] <= 0).sum(), (df["Ride Distance"] <= 0).sum()

(np.int64(0), np.int64(0), np.int64(0), np.int64(0))

In [55]:
df[["Driver Ratings", "Customer Rating"]].agg(["min", "max"])

     Driver Ratings  Customer Rating
min             3.0              3.0
max             5.0              5.0

In [56]:
df["Payment Method"].value_counts(dropna=False)

Payment Method
NaN            48000
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

In [57]:
df["Vehicle Type"].value_counts()

Vehicle Type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

In [58]:
df["Driver Cancellation Reason"].value_counts(dropna=False)

Driver Cancellation Reason
NaN                                    123000
Customer related issue                   6837
The customer was coughing/sick           6751
Personal & Car related issues            6726
More than permitted people in there      6686
Name: count, dtype: int64

In [59]:
df["Reason for cancelling by Customer"].value_counts(dropna=False)

Reason for cancelling by Customer
NaN                                             139500
Wrong Address                                     2362
Change of plans                                   2353
Driver is not moving towards pickup location      2335
Driver asked to cancel                            2295
AC is not working                                 1155
Name: count, dtype: int64

In [60]:
df["Incomplete Rides Reason"].value_counts(dropna=False)

Incomplete Rides Reason
NaN                  141000
Customer Demand        3040
Vehicle Breakdown      3012
Other Issue            2948
Name: count, dtype: int64

In [61]:
df.duplicated().sum()

np.int64(0)

In [63]:
import os
print(os.getcwd())
print(os.path.exists("data"))

F:\Driver_Quality_&_Service_Performance_Analytics
False

In [64]:
os.listdir()

['.venv',
 'driver_quality_&_service_performance_analytics.ipynb',
 'ncr_ride_bookings.csv']

In [66]:
df.to_csv("uber_data_cleaned.csv", index=False)

In [67]:
import os
print(os.path.exists("uber_data_cleaned.csv"))

True

In [68]:
pd.read_csv("uber_data_cleaned.csv").shape

(150000, 21)

In [69]:
df["Month"] = df["Date"].dt.month

In [70]:
df[["Date", "Month"]].head()

        Date  Month
0 2024-03-23      3
1 2024-11-29     11
2 2024-08-23      8
3 2024-10-21     10
4 2024-09-16      9

In [71]:
df["Day_of_Week"] = df["Date"].dt.day_name()

In [72]:
df[["Date", "Day_of_Week"]].head()

        Date Day_of_Week
0 2024-03-23    Saturday
1 2024-11-29      Friday
2 2024-08-23      Friday
3 2024-10-21      Monday
4 2024-09-16      Monday

In [73]:
df["Hour"] = df["Time"].dt.hour

In [74]:
df[["Time", "Hour"]].head()

                 Time  Hour
0 1900-01-01 12:29:38    12
1 1900-01-01 18:01:39    18
2 1900-01-01 08:56:10     8
3 1900-01-01 17:17:25    17
4 1900-01-01 22:08:00    22

In [75]:
df["Time_Period"] = pd.cut(
    df["Hour"],
    bins=[-1, 5, 11, 16, 20, 23],
    labels=["Night", "Morning", "Afternoon", "Evening", "Late Night"]
)

In [76]:
df[["Hour", "Time_Period"]].head(10)

   Hour Time_Period
0    12   Afternoon
1    18     Evening
2     8     Morning
3    17     Evening
4    22  Late Night
5     9     Morning
6    15   Afternoon
7    17     Evening
8    12   Afternoon
9    19     Evening

In [77]:
df["Is_Completed"] = (df["Booking Status"] == "Completed").astype(int)

In [78]:
df[["Booking Status", "Is_Completed"]].head(10)

    Booking Status  Is_Completed
0  No Driver Found             0
1       Incomplete             0
2        Completed             1
3        Completed             1
4        Completed             1
5        Completed             1
6        Completed             1
7        Completed             1
8  No Driver Found             0
9       Incomplete             0

In [79]:
df["Is_Driver_Cancelled"] = (df["Booking Status"] == "Cancelled by Driver").astype(int)

In [80]:
df[["Booking Status", "Is_Driver_Cancelled"]].head(10)

    Booking Status  Is_Driver_Cancelled
0  No Driver Found                    0
1       Incomplete                    0
2        Completed                    0
3        Completed                    0
4        Completed                    0
5        Completed                    0
6        Completed                    0
7        Completed                    0
8  No Driver Found                    0
9       Incomplete                    0

In [81]:
df["Is_Driver_Cancelled"].value_counts()

Is_Driver_Cancelled
0    123000
1     27000
Name: count, dtype: int64

In [82]:
df["Is_Customer_Cancelled"] = (df["Booking Status"] == "Cancelled by Customer").astype(int)

In [83]:
df["Is_Customer_Cancelled"].value_counts()

Is_Customer_Cancelled
0    139500
1     10500
Name: count, dtype: int64

In [84]:
df["Is_Incomplete"] = (df["Booking Status"] == "Incomplete").astype(int)

In [85]:
df["Is_Incomplete"].value_counts()

Is_Incomplete
0    141000
1      9000
Name: count, dtype: int64

In [86]:
df.to_csv("uber_data_cleaned.csv", index=False)

In [87]:
pd.read_csv("uber_data_cleaned.csv").shape

(150000, 29)

In [88]:
df["Is_Weekend"] = df["Day_of_Week"].isin(["Saturday", "Sunday"]).astype(int)

In [89]:
df["Is_Weekend"].value_counts()

Is_Weekend
0    107060
1     42940
Name: count, dtype: int64

In [90]:
df["Driver_Rating_Band"] = pd.cut(
    df["Driver Ratings"],
    bins=[2.9, 3.9, 4.4, 5.0],
    labels=["Low", "Average", "High"]
)

In [91]:
df[["Driver Ratings", "Driver_Rating_Band"]].dropna().head(10)

    Driver Ratings Driver_Rating_Band
2              4.9               High
3              4.6               High
4              4.1            Average
5              4.1            Average
6              4.0            Average
7              4.4            Average
10             4.2            Average
13             4.1            Average
14             4.7               High
15             4.0            Average

In [92]:
df["VTAT_Band"] = pd.cut(
    df["Avg VTAT"],
    bins=[0, 5, 10, 15, float("inf")],
    labels=["Fast", "Moderate", "Slow", "Very Slow"]
)

In [93]:
df[["Avg VTAT", "VTAT_Band"]].dropna().head(10)

    Avg VTAT VTAT_Band
1        4.9      Fast
2       13.4      Slow
3       13.1      Slow
4        5.3  Moderate
5        5.1  Moderate
6        7.1  Moderate
7       12.1      Slow
9        6.1  Moderate
10       7.7  Moderate
12       4.6      Fast

In [94]:
df["CTAT_Band"] = pd.cut(
    df["Avg CTAT"],
    bins=[0, 20, 30, 40, float("inf")],
    labels=["Fast", "Moderate", "Slow", "Very Slow"]
)

In [95]:
df[["Avg CTAT", "CTAT_Band"]].dropna().head(10)

    Avg CTAT CTAT_Band
1       14.0      Fast
2       25.8  Moderate
3       28.5  Moderate
4       19.6      Fast
5       18.1      Fast
6       20.4  Moderate
7       16.5      Fast
9       26.0  Moderate
10      18.9      Fast
13      28.2  Moderate

In [96]:
df["Distance_Band"] = pd.cut(
    df["Ride Distance"],
    bins=[0, 5, 15, 30, float("inf")],
    labels=["Short", "Medium", "Long", "Very Long"]
)

In [97]:
df[["Ride Distance", "Distance_Band"]].dropna().head(10)

    Ride Distance Distance_Band
1            5.73        Medium
2           13.58        Medium
3           34.02     Very Long
4           48.21     Very Long
5            4.85         Short
6           41.24     Very Long
7            6.56        Medium
9           10.36        Medium
10          19.84          Long
13          21.44          Long

In [98]:
df.to_csv("uber_data_cleaned.csv", index=False)

In [99]:
pd.read_csv("uber_data_cleaned.csv").shape

(150000, 34)

In [100]:
df["Booking Status"].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [101]:
df["Booking Status"].value_counts()

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [104]:
df[[
    "Avg VTAT",
    "Avg CTAT",
    "Booking Value",
    "Ride Distance",
    "Driver Ratings",
    "Customer Rating"
]].describe()

,Avg VTAT,Avg CTAT,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,4277.000000,50.000000,5.000000,5.000000

In [105]:
pd.crosstab(
    df["Vehicle Type"],
    df["Booking Status"],
    normalize="index"
).round(3) * 100

Booking Status,Cancelled by Customer,Cancelled by Driver,Completed,Incomplete,No Driver Found
Vehicle Type,,,,,
Auto,7.2,17.8,61.9,6.0,7.2
Bike,7.0,18.1,62.3,5.9,6.7
Go Mini,7.0,17.9,62.2,6.1,6.8
Go Sedan,6.7,18.5,61.4,6.0,7.2
Premier Sedan,7.0,17.9,62.1,5.9,7.1
Uber XL,7.3,17.1,62.6,5.9,7.1
eBike,6.8,18.1,62.1,6.0,7.1

In [106]:
pd.crosstab(
    df["Time_Period"],
    df["Booking Status"],
    normalize="index"
).round(3) * 100

Booking Status,Cancelled by Customer,Cancelled by Driver,Completed,Incomplete,No Driver Found
Time_Period,,,,,
Night,6.9,18.4,62.2,5.5,7.2
Morning,6.9,17.8,62.2,6.0,7.0
Afternoon,7.1,18.1,61.7,6.1,7.0
Evening,7.0,18.1,61.8,6.1,7.0
Late Night,7.0,17.7,62.4,6.0,6.8

In [107]:
df.loc[
    df["Booking Status"] == "Cancelled by Driver",
    "Driver Cancellation Reason"
].value_counts()

Driver Cancellation Reason
Customer related issue                 6837
The customer was coughing/sick         6751
Personal & Car related issues          6726
More than permitted people in there    6686
Name: count, dtype: int64

In [108]:
pd.crosstab(
    df["VTAT_Band"],
    df["Booking Status"],
    normalize="index"
).round(3) * 100

Booking Status,Cancelled by Customer,Cancelled by Driver,Completed,Incomplete
VTAT_Band,,,,
Fast,0.1,19.8,69.2,10.9
Moderate,5.9,25.0,59.9,9.3
Slow,7.7,13.1,79.2,0.0
Very Slow,100.0,0.0,0.0,0.0

In [109]:
df["VTAT_Band"].value_counts(dropna=False)

VTAT_Band
Moderate     59896
Slow         44772
Fast         31311
NaN          10500
Very Slow     3521
Name: count, dtype: int64

In [110]:
df.loc[
    df["VTAT_Band"] == "Very Slow",
    ["Avg VTAT", "Booking Status", "Reason for cancelling by Customer"]
].head(20)

,Avg VTAT,Booking Status,Reason for cancelling by Customer
62,16.6,Cancelled by Customer,Driver is not moving towards pickup location
153,19.1,Cancelled by Customer,Change of plans
156,18.5,Cancelled by Customer,Change of plans
157,16.1,Cancelled by Customer,Driver asked to cancel
238,16.9,Cancelled by Customer,Change of plans
386,16.9,Cancelled by Customer,Change of plans
393,16.2,Cancelled by Customer,Change of plans
492,19.2,Cancelled by Customer,Driver asked to cancel
501,18.0,Cancelled by Customer,Change of plans
635,20.0,Cancelled by Customer,Change of plans
711,17.6,Cancelled by Customer,Wrong Address
728,15.7,Cancelled by Customer,AC is not working
920,16.5,Cancelled by Customer,Driver is not moving towards pickup location
936,15.9,Cancelled by Customer,Change of plans
998,19.6,Cancelled by Customer,Driver asked to cancel
1000,19.9,Cancelled by Customer,AC is not working
1008,19.2,Cancelled by Customer,Change of plans
1049,19.2,Cancelled by Customer,Wrong Address
1062,19.8,Cancelled by Customer,Wrong Address
1095,16.0,Cancelled by Customer,Driver is not moving towards pickup location

In [111]:
df.groupby("VTAT_Band", observed=True)["Is_Customer_Cancelled"].agg(
    ["count", "sum", "mean"]
).assign(
    Customer_Cancellation_Rate=lambda x: x["mean"] * 100
).round(2)

           count   sum  mean  Customer_Cancellation_Rate
VTAT_Band
Fast       31311    33  0.00                        0.11
Moderate   59896  3508  0.06                        5.86
Slow       44772  3438  0.08                        7.68
Very Slow   3521  3521  1.00                      100.00

In [112]:
df.groupby("VTAT_Band", observed=True)["Is_Driver_Cancelled"].agg(
    ["count", "sum", "mean"]
).assign(
    Driver_Cancellation_Rate=lambda x: x["mean"] * 100
).round(2)

           count    sum  mean  Driver_Cancellation_Rate
VTAT_Band
Fast       31311   6188  0.20                     19.76
Moderate   59896  14959  0.25                     24.97
Slow       44772   5853  0.13                     13.07
Very Slow   3521      0  0.00                      0.00

In [113]:
df.groupby("CTAT_Band", observed=True)["Booking Status"].value_counts(
    normalize=True
).mul(100).round(2)

CTAT_Band  Booking Status
Fast       Completed          77.43
           Incomplete         22.57
Moderate   Completed          87.37
           Incomplete         12.63
Slow       Completed         100.00
Very Slow  Completed         100.00
Name: proportion, dtype: float64

In [114]:
df["CTAT_Band"].value_counts(dropna=False)

CTAT_Band
NaN          48000
Moderate     35517
Slow         31047
Fast         19994
Very Slow    15442
Name: count, dtype: int64

In [115]:
df.groupby("CTAT_Band", observed=True)["Avg CTAT"].agg(
    ["count", "min", "mean", "median", "max"]
).round(2)

           count   min   mean  median   max
CTAT_Band
Fast       19994  10.0  16.96    17.2  20.0
Moderate   35517  20.1  25.04    25.0  30.0
Slow       31047  30.1  35.04    35.0  40.0
Very Slow  15442  40.1  42.53    42.5  45.0

In [116]:
df.groupby("CTAT_Band", observed=True)["Is_Incomplete"].agg(
    ["count", "sum", "mean"]
).assign(
    Incomplete_Rate=lambda x: x["mean"] * 100
).round(2)

           count   sum  mean  Incomplete_Rate
CTAT_Band
Fast       19994  4513  0.23            22.57
Moderate   35517  4487  0.13            12.63
Slow       31047     0  0.00             0.00
Very Slow  15442     0  0.00             0.00

In [117]:
pd.crosstab(
    df["VTAT_Band"],
    df["Booking Status"]
)

Booking Status,Cancelled by Customer,Cancelled by Driver,Completed,Incomplete
VTAT_Band,,,,
Fast,33,6188,21670,3420
Moderate,3508,14959,35849,5580
Slow,3438,5853,35481,0
Very Slow,3521,0,0,0

In [118]:
df.groupby("Booking Status")["Avg VTAT"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

                       count   mean  median  min   max
Booking Status
Cancelled by Customer  10500  12.51    12.6  5.0  20.0
Cancelled by Driver    27000   7.50     7.5  3.0  12.0
Completed              93000   8.51     8.5  2.0  15.0
Incomplete              9000   6.01     6.0  2.0  10.0
No Driver Found            0    NaN     NaN  NaN   NaN

In [119]:
df["Pickup Location"].nunique(), df["Drop Location"].nunique()

(176, 176)

In [120]:
df["Pickup Location"].value_counts().head(10)

Pickup Location
Khandsa             949
Barakhamba Road     946
Saket               931
Badarpur            921
Pragati Maidan      920
Madipur             919
AIIMS               918
Mehrauli            915
Dwarka Sector 21    914
Pataudi Chowk       907
Name: count, dtype: int64

In [121]:
df["Pickup Location"].value_counts().describe().round(2)

count    176.00
mean     852.27
std       30.07
min      790.00
25%      830.00
50%      849.50
75%      869.25
max      949.00
Name: count, dtype: float64

In [122]:
df.groupby("Pickup Location")["Is_Driver_Cancelled"].agg(
    ["count", "sum", "mean"]
).assign(
    Driver_Cancellation_Rate=lambda x: x["mean"] * 100
).sort_values(
    "Driver_Cancellation_Rate",
    ascending=False
).head(10).round(2)

                 count  sum  mean  Driver_Cancellation_Rate
Pickup Location
Nehru Place        885  190  0.21                     21.47
Vinobapuri         823  176  0.21                     21.39
GTB Nagar          872  183  0.21                     20.99
Munirka            815  171  0.21                     20.98
Qutub Minar        823  172  0.21                     20.90
Chhatarpur         829  173  0.21                     20.87
Rajouri Garden     852  176  0.21                     20.66
Shivaji Park       900  185  0.21                     20.56
Shahdara           820  168  0.20                     20.49
Vatika Chowk       833  170  0.20                     20.41

In [123]:
df.groupby("Pickup Location")["Is_Driver_Cancelled"].agg(
    ["count", "sum", "mean"]
).assign(
    Driver_Cancellation_Rate=lambda x: x["mean"] * 100
).sort_values(
    "Driver_Cancellation_Rate",
    ascending=True
).head(10).round(2)

                     count  sum  mean  Driver_Cancellation_Rate
Pickup Location
Kanhaiya Nagar         895  130  0.15                     14.53
Seelampur              832  124  0.15                     14.90
Hauz Khas              876  132  0.15                     15.07
Peeragarhi             861  132  0.15                     15.33
IMT Manesar            840  129  0.15                     15.36
Jama Masjid            849  132  0.16                     15.55
Sadar Bazar Gurgaon    817  128  0.16                     15.67
Welcome                836  132  0.16                     15.79
Ghitorni Village       790  125  0.16                     15.82
Yamuna Bank            824  131  0.16                     15.90

In [124]:
df.groupby("Pickup Location")["Is_Customer_Cancelled"].agg(
    ["count", "sum", "mean"]
).assign(
    Customer_Cancellation_Rate=lambda x: x["mean"] * 100
).sort_values(
    "Customer_Cancellation_Rate",
    ascending=False
).head(10).round(2)

                    count  sum  mean  Customer_Cancellation_Rate
Pickup Location
Seelampur             832   81  0.10                        9.74
Preet Vihar           832   80  0.10                        9.62
Akshardham            839   78  0.09                        9.30
Arjangarh             810   74  0.09                        9.14
Keshav Puram          865   79  0.09                        9.13
Kashmere Gate ISBT    838   74  0.09                        8.83
Saket A Block         823   72  0.09                        8.75
Mansarovar Park       877   75  0.09                        8.55
Indraprastha          850   71  0.08                        8.35
Greater Noida         866   72  0.08                        8.31

In [125]:
location_analysis = df.groupby("Pickup Location").agg(
    Bookings=("Booking ID", "count"),
    Driver_Cancellation_Rate=("Is_Driver_Cancelled", "mean"),
    Customer_Cancellation_Rate=("Is_Customer_Cancelled", "mean"),
    Incomplete_Rate=("Is_Incomplete", "mean")
)

location_analysis[
    [
        "Driver_Cancellation_Rate",
        "Customer_Cancellation_Rate",
        "Incomplete_Rate"
    ]
] = (
    location_analysis[
        [
            "Driver_Cancellation_Rate",
            "Customer_Cancellation_Rate",
            "Incomplete_Rate"
        ]
    ] * 100
)

location_analysis.round(2).head()

,Bookings,Driver_Cancellation_Rate,Customer_Cancellation_Rate,Incomplete_Rate
Pickup Location,,,,
AIIMS,918,19.17,6.54,6.21
Adarsh Nagar,858,16.43,7.23,6.88
Akshardham,839,20.26,9.30,7.27
Ambience Mall,873,17.30,6.64,6.07
Anand Vihar,859,16.53,6.64,4.42

In [126]:
location_analysis["Non_Completion_Rate"] = (
    1 - df.groupby("Pickup Location")["Is_Completed"].mean()
) * 100

location_analysis.round(2).head()

,Bookings,Driver_Cancellation_Rate,Customer_Cancellation_Rate,Incomplete_Rate,Non_Completion_Rate
Pickup Location,,,,,
AIIMS,918,19.17,6.54,6.21,38.78
Adarsh Nagar,858,16.43,7.23,6.88,37.76
Akshardham,839,20.26,9.30,7.27,43.86
Ambience Mall,873,17.30,6.64,6.07,36.77
Anand Vihar,859,16.53,6.64,4.42,35.62

In [127]:
location_analysis.sort_values(
    "Non_Completion_Rate",
    ascending=False
).head(10).round(2)

,Bookings,Driver_Cancellation_Rate,Customer_Cancellation_Rate,Incomplete_Rate,Non_Completion_Rate
Pickup Location,,,,,
Vinobapuri,823,21.39,8.26,6.44,45.32
Akshardham,839,20.26,9.30,7.27,43.86
Chhatarpur,829,20.87,6.63,6.76,41.86
Badshahpur,868,19.01,8.06,6.57,41.71
Pragati Maidan,920,19.46,7.50,6.96,41.52
Netaji Subhash Place,830,20.36,6.87,5.66,41.33
Vatika Chowk,833,20.41,6.60,6.12,41.30
Faridabad Sector 15,831,19.74,8.30,5.29,41.28
Indirapuram,854,19.91,6.67,6.32,41.10
IFFCO Chowk,830,18.80,7.83,6.63,40.84

In [128]:
location_analysis.sort_values(
    "Non_Completion_Rate",
    ascending=True
).head(10).round(2)

,Bookings,Driver_Cancellation_Rate,Customer_Cancellation_Rate,Incomplete_Rate,Non_Completion_Rate
Pickup Location,,,,,
Welcome,836,15.79,7.78,5.14,33.73
Subhash Chowk,887,16.01,5.41,5.98,34.39
Yamuna Bank,824,15.90,6.92,6.55,35.19
IMT Manesar,840,15.36,7.50,6.55,35.24
RK Puram,850,17.29,5.76,6.71,35.29
Sushant Lok,850,17.06,6.00,5.29,35.41
Subhash Nagar,861,16.14,6.39,6.04,35.54
Anand Vihar,859,16.53,6.64,4.42,35.62
Laxmi Nagar,797,16.69,7.53,5.14,35.63
Gurgaon Sector 29,824,16.50,5.70,5.34,35.68

In [129]:
df["Drop Location"].value_counts().describe().round(2)

count    176.00
mean     852.27
std       28.82
min      774.00
25%      835.75
50%      850.50
75%      870.25
max      936.00
Name: count, dtype: float64

In [130]:
pd.crosstab(
    df["Day_of_Week"],
    df["Booking Status"],
    normalize="index"
).round(3) * 100

Booking Status,Cancelled by Customer,Cancelled by Driver,Completed,Incomplete,No Driver Found
Day_of_Week,,,,,
Friday,7.3,17.7,61.9,5.9,7.2
Monday,7.0,18.7,61.5,6.0,6.8
Saturday,6.7,18.0,62.4,6.0,6.9
Sunday,7.0,17.9,62.2,5.9,6.9
Thursday,7.0,17.7,62.2,6.1,7.0
Tuesday,6.9,18.3,61.6,6.2,7.0
Wednesday,7.1,17.8,62.1,5.9,7.2

In [131]:
df["Driver Ratings"].value_counts().sort_index()

Driver Ratings
3.0      745
3.1     1459
3.2     1538
3.3     1461
3.4     1491
3.5      748
3.6     2026
3.7     3790
3.8     3848
3.9     3915
4.0     1995
4.1     6966
4.2    13841
4.3    14081
4.4     7018
4.5     4634
4.6     9368
4.7     4678
4.8     2328
4.9     4705
5.0     2365
Name: count, dtype: int64

In [132]:
df[df["Booking Status"] == "Completed"].groupby(
    "Driver Ratings"
)[["Avg VTAT", "Avg CTAT", "Booking Value", "Ride Distance"]].mean().round(2)

                Avg VTAT  Avg CTAT  Booking Value  Ride Distance
Driver Ratings
3.0                 8.66     30.12         521.87          25.41
3.1                 8.65     29.71         519.88          26.04
3.2                 8.47     29.80         501.75          26.31
3.3                 8.53     30.19         506.02          26.37
3.4                 8.57     30.16         501.17          25.58
3.5                 8.55     30.49         509.73          26.69
3.6                 8.44     29.77         504.72          26.26
3.7                 8.52     30.15         504.23          25.94
3.8                 8.55     30.18         509.75          26.02
3.9                 8.50     29.96         511.26          26.28
4.0                 8.63     30.20         526.09          25.88
4.1                 8.51     30.05         500.30          25.82
4.2                 8.48     29.98         506.56          25.92
4.3                 8.52     30.09         510.33          26.10
4.4                 8.55     29.96         509.85          26.15
4.5                 8.55     29.97         509.70          25.94
4.6                 8.53     29.98         506.78          25.86
4.7                 8.41     30.01         508.56          25.87
4.8                 8.45     30.19         514.20          26.18
4.9                 8.47     30.18         507.64          25.99
5.0                 8.44     29.95         504.47          26.03

In [133]:
completed = df[df["Booking Status"] == "Completed"].copy()

completed["Driver_Rating_Band"] = pd.cut(
    completed["Driver Ratings"],
    bins=[2.9, 3.9, 4.4, 5.0],
    labels=["Low", "Average", "High"]
)

completed.groupby("Driver_Rating_Band", observed=True).agg(
    Drivers_Rated=("Driver Ratings", "count"),
    Avg_VTAT=("Avg VTAT", "mean"),
    Avg_CTAT=("Avg CTAT", "mean"),
    Avg_Booking_Value=("Booking Value", "mean"),
    Avg_Ride_Distance=("Ride Distance", "mean")
).round(2)

,Drivers_Rated,Avg_VTAT,Avg_CTAT,Avg_Booking_Value,Avg_Ride_Distance
Driver_Rating_Band,,,,,
Low,21021,8.53,30.04,508.23,26.10
Average,43901,8.52,30.03,508.19,25.99
High,28078,8.49,30.03,508.12,25.94

In [134]:
df.groupby("Driver_Rating_Band", observed=True).agg(
    Rides_Rated=("Driver Ratings", "count"),
    Driver_Cancellation_Rate=("Is_Driver_Cancelled", "mean"),
    Customer_Cancellation_Rate=("Is_Customer_Cancelled", "mean"),
    Incomplete_Rate=("Is_Incomplete", "mean")
).assign(
    Driver_Cancellation_Rate=lambda x: x["Driver_Cancellation_Rate"] * 100,
    Customer_Cancellation_Rate=lambda x: x["Customer_Cancellation_Rate"] * 100,
    Incomplete_Rate=lambda x: x["Incomplete_Rate"] * 100
).round(2)

,Rides_Rated,Driver_Cancellation_Rate,Customer_Cancellation_Rate,Incomplete_Rate
Driver_Rating_Band,,,,
Low,21021,0.0,0.0,0.0
Average,43901,0.0,0.0,0.0
High,28078,0.0,0.0,0.0

In [135]:
df["Customer Rating"].value_counts().sort_index()

Customer Rating
3.0      468
3.1     1008
3.2      881
3.3      900
3.4      928
3.5      443
3.6     1194
3.7     2354
3.8     2357
3.9     2370
4.0     1185
4.1     5396
4.2    10697
4.3    10995
4.4     5279
4.5     5890
4.6    11533
4.7     5763
4.8     5880
4.9    11642
5.0     5837
Name: count, dtype: int64

In [136]:
df[df["Booking Status"] == "Completed"][
    ["Driver Ratings", "Customer Rating"]
].corr().round(3)

                 Driver Ratings  Customer Rating
Driver Ratings            1.000           -0.001
Customer Rating          -0.001            1.000

In [137]:
pd.crosstab(
    df.loc[df["Booking Status"] == "Cancelled by Driver", "Pickup Location"],
    df.loc[df["Booking Status"] == "Cancelled by Driver", "Driver Cancellation Reason"],
    normalize="index"
).round(3).head(10) * 100

Driver Cancellation Reason,Customer related issue,More than permitted people in there,Personal & Car related issues,The customer was coughing/sick
Pickup Location,,,,
AIIMS,19.9,27.8,23.9,28.4
Adarsh Nagar,17.0,27.7,27.0,28.4
Akshardham,25.3,28.2,15.9,30.6
Ambience Mall,17.9,23.8,30.5,27.8
Anand Vihar,23.2,22.5,26.1,28.2
Anand Vihar ISBT,23.6,27.9,23.6,25.0
Ardee City,21.5,23.6,28.5,26.4
Arjangarh,25.9,26.7,23.0,24.4
Ashok Park Main,26.5,30.5,25.2,17.9
Ashok Vihar,32.2,26.6,21.0,20.3

In [138]:
driver_cancel_reasons = (
    df.loc[df["Booking Status"] == "Cancelled by Driver",
           "Driver Cancellation Reason"]
    .value_counts()
)

driver_cancel_reasons.to_frame("Count").assign(
    Percentage=lambda x: (
        x["Count"] / x["Count"].sum() * 100
    ).round(2)
)

                                     Count  Percentage
Driver Cancellation Reason
Customer related issue                6837       25.32
The customer was coughing/sick        6751       25.00
Personal & Car related issues         6726       24.91
More than permitted people in there   6686       24.76

In [139]:
monthly_status = pd.crosstab(
    df["Month"],
    df["Booking Status"],
    normalize="index"
).round(3) * 100

monthly_status

Booking Status,Cancelled by Customer,Cancelled by Driver,Completed,Incomplete,No Driver Found
Month,,,,,
1,6.9,18.1,61.8,6.3,6.9
2,7.0,18.4,61.8,5.7,7.1
3,7.1,17.6,62.5,5.7,7.0
4,6.4,18.2,62.6,5.9,6.9
5,7.2,18.1,61.9,6.0,6.8
6,7.1,17.7,62.4,5.9,6.9
7,7.2,18.1,61.5,6.2,7.0
8,6.6,18.6,61.6,5.8,7.4
9,7.3,17.7,61.6,6.1,7.4
10,7.1,17.6,62.5,6.0,6.9
11,7.0,17.9,61.8,6.4,6.9
12,7.1,18.0,62.2,5.9,6.8

In [140]:
df.groupby("Booking Status")["Booking Value"].agg(
    ["count", "sum", "mean", "median"]
).round(2)

                       count         sum    mean  median
Booking Status
Cancelled by Customer      0         0.0     NaN     NaN
Cancelled by Driver        0         0.0     NaN     NaN
Completed              93000  47260574.0  508.18   414.0
Incomplete              9000   4585609.0  509.51   414.0
No Driver Found            0         0.0     NaN     NaN

In [ ]:
# Install these dependencies through your selected Python environment before running the notebook:
# sqlalchemy
# psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.9.13)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\User\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

Requirement already satisfied: sqlalchemy in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.0.54)
Requirement already satisfied: greenlet>=1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)

In [ ]:
import getpass
import os
from sqlalchemy import create_engine

username = os.getenv("PGUSER", "postgres")
password = os.getenv("PGPASSWORD") or getpass.getpass("PostgreSQL password: ")
host = "127.0.0.1"
port = os.getenv("PGPORT", "5432")
database = os.getenv("PGDATABASE", "driver_quality")

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

table_name = "uber_data_cleaned"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'uber_data_cleaned' in database 'driver_quality'.